# See https://redocly.com/docs/cli/configuration/

apis:
  # Update the apiName with your actual API name, and the version with your actual API version.
  Connectv1:
    # Update the path to your OpenAPI root file
    root: ./cs_connect1-15.yaml
    

rules:
  # A sample custom rule. Read more about rules: https://redocly.com/docs/cli/rules/
  assert/operation-description:
    subject: 
      type: Operation
      property: description
    assertions:
      defined: true
      minLength: 30
      pattern: ^[A-Z].+(\.|\.)$

features.openapi:
  generateCodeSamples:
    languages:
      - lang: curl
      - lang: Node.js
      - lang: Python


